import Head from "next/head";
import ColorPicker from "../components/ColorPicker";

export default function Home() {
  return (
    <div>
      <Head>
        <title>PaintPicker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ColorPicker />
    </div>
  );
}
